version: '3'
services:
  # db:
  #   image: mysql:5.7
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Thao1995
  web:
    # depends_on:
    #   - db
    build: .
    user: root
    restart: unless-stopped
    command: >
      bash -c "bundle install &&
               bundle exec rake db:create &&
               bundle exec rake db:migrate &&
               bundle exec rake assets:precompile &&
               bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      # MYSQL_USER: root
      # MYSQL_PASSWORD: Thao1995
      # MYSQL_HOST: db
      # MYSQL_PORT: 3306
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
    volumes:
      - "./:/demo_app"
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    links:
      - web:web
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/html:/etc/nginx/html
volumes:
  .:
