version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    working_directory: ~/Reactjs-App
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: "123456"
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: "123456"
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: set up db
          command: bundle exec rails db:create db:migrate
      - run:
          name: run rspec
          command: bundle exec rspec
